# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  # Directory where the build system installs dependencies
  # and runs your build. Store your package.json, .nvmrc, etc here.
  # If not set, defaults to the root directory.
  base = "/"
  command = "npm run build"
  publish = "dist/"

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

