# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  # Directory where the build system installs dependencies
  # and runs your build. Store your package.json, .nvmrc, etc here.
  # If not set, defaults to the root directory.
  base = "/"

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
from = "/main/*"
to = "/main/*"
status = 200
force = true

[[redirects]]
from = "/my_music/*"
to = "/my_music/*"
status = 200
force = true

[[redirects]]
from = "/tracks/*"
to = "/tracks/*"
status = 200
force = true

[[redirects]]
from = "/creators/*"
to = "/creators/*"
status = 200
force = true

[[redirects]]
from = "/other/*"
to = "/other/*"
status = 200
force = true

[[redirects]]
from = "/register/*"
to = "/register/*"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/"
status = 200
force = true

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

